# Copy this to docker-compose.override.yml and customize as necessary
version: '2'

services:
  server:
    # Example override for using the sandbox proxy instead of prod
    environment:
      - PROXY=https://alliance-primo.hosted.exlibrisgroup.com:443

    # Expose ports to your host - this is pretty much a must, but it's in the
    # override because ports defined in the main docker-compose.yml cannot be
    # removed, just added to
    ports:
      # The http server is on port 8003, so we map that to 80 on the host machine
      - 80:8003
      # 3001 serves up a "browsersync" thing.  Use at your peril.
      #- 3001:3001

    # If you want real-time changes, this mounts all custom stuff (e.g.,
    # `custom/UO`) into the running container
    volumes:
      - ./custom:/home/node/primo-explore-devenv/primo-explore/custom
