version: '2'

services:
  server:
    build: .
    environment:
      - PROXY=https://alliance-uoregon.primo.exlibrisgroup.com:443
      - VIEW=01ALLIANCE_UO-UO
    volumes:
      - ./packages:/home/node/primo-explore-devenv/packages

  codeshift:
    build:
      context: .
      dockerfile: codeshift/Dockerfile
    volumes:
      - ./codeshift:/var/local/codeshift
      - ./custom:/var/local/custom
