version: '2'

services:
  server:
    build: .
    environment:
      - PROXY=https://alliance-primo-sb.hosted.exlibrisgroup.com:443
      - VIEW=UO
    volumes:
      - ./packages:/home/node/primo-explore-devenv/packages
